# Generated by Django 4.1.4 on 2022-12-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_active',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='Активный'),
        ),
    ]
